#!/bin/bash

set -eu

/usr/bin/s3cmd sync /home/backup/mysql_backups s3://attic.okfn.org/ --config=/home/okfn/.s3 2>&1 > /home/backup/$(date +%s)_mysql_backup.log
/usr/bin/s3cmd sync /home/backup/psql_backups s3://attic.okfn.org/ --config=/home/okfn/.s3 2>&1 > /home/backup/$(date +%s)_psql_backup.log
find /home/backup/mysql_backups -mtime +14 -exec rm {} \;
find /home/backup/psql_backups -mtime +14 -exec rm {} \;
