{
  "bkn-1": {
    "aws_id": "i-29720e42", 
    "created": "2010-04-26", 
    "ip": "184.73.208.200", 
    "ip2": "ec2-184-73-208-200.compute-1.amazonaws.com us-east-1d", 
    "location": "us-east-1d", 
    "owner": "bkn", 
    "provider": "aws", 
    "spec": "m1.small", 
    "type": "ec2"
  }, 
  "bkn-2": {
    "aws_id": "i-b18dbbda", 
    "created": "2010-05-27", 
    "ip": "184.73.164.129", 
    "location": "us-east-1d", 
    "notes": "krichel", 
    "owner": "bkn", 
    "provider": "aws", 
    "spec": "m1.small", 
    "type": "ec2"
  }, 
  "epsi": {
    "cost per month": null, 
    "created": "2011-02", 
    "ip": "178.79.153.167", 
    "ip2": "epsiplatform.okfn.org", 
    "location": "linode-UK", 
    "owner": "epsi", 
    "provider": "linode", 
    "spec": "linode512", 
    "type": "dedicated-virtual"
  }, 
  "eu0": {
    "cost per month": "49", 
    "created": "2007", 
    "location": "de", 
    "notes": null, 
    "owner": "okfn", 
    "provider": "hentzner", 
    "spec": "", 
    "type": "dedicated"
  }, 
  "eu1": {
    "cost per month": null, 
    "created": "2008", 
    "location": "uk", 
    "notes": null, 
    "owner": "okfn", 
    "provider": "bytemark", 
    "spec": null, 
    "type": "dedicated-virtual"
  }, 
  "eu10": {
    "aws_id": "i-03c9e674", 
    "aws_private_dns_name": "ip-10-48-110-205.eu-west-1.compute.internal", 
    "aws_public_dns_name": "ec2-79-125-44-1.eu-west-1.compute.amazonaws.com", 
    "created": "2010-11-11T22:28:33", 
    "instance_type": "t1.micro", 
    "location": "eu-west-1", 
    "notes": null, 
    "os": "ubuntu-maverick-64-ebs", 
    "owner": "okfn", 
    "placement": "eu-west-1b", 
    "provider": "aws", 
    "security_groups": [
      "default", 
      "www-only", 
      "ssh-only", 
      "munin-only", 
      "instance-da69cda3-34e7-495c-ac12-7637228cbb19"
    ], 
    "type": "ec2", 
    "volumes": {}
  }, 
  "eu11": {
    "aws_id": "i-1da28b6a", 
    "aws_private_dns_name": "ip-10-227-139-160.eu-west-1.compute.internal", 
    "aws_public_dns_name": "ec2-79-125-70-61.eu-west-1.compute.amazonaws.com", 
    "created": "2010-11-14T21:24:09", 
    "instance_type": "m1.large", 
    "location": "eu-west-1", 
    "notes": null, 
    "os": "ubuntu-lucid-64", 
    "owner": "okfn", 
    "placement": "eu-west-1b", 
    "provider": "aws", 
    "security_groups": [
      "default", 
      "www-only", 
      "ssh-only", 
      "munin-only", 
      "instance-ef88b072-b285-422f-bc50-ed50a044f150"
    ], 
    "type": "ec2", 
    "volumes": {}
  }, 
  "eu12": {
    "aws_id": "i-b46a59c3", 
    "aws_private_dns_name": "ip-10-226-107-164.eu-west-1.compute.internal", 
    "aws_public_dns_name": "ec2-46-51-142-222.eu-west-1.compute.amazonaws.com", 
    "created": "2010-11-27T19:46:29", 
    "instance_type": "t1.micro", 
    "location": "eu-west-1", 
    "notes": null, 
    "os": "ubuntu-lucid-64-ebs", 
    "owner": "okfn", 
    "placement": "eu-west-1b", 
    "provider": "aws", 
    "security_groups": [
      "default", 
      "www-only", 
      "ssh-only", 
      "munin-only", 
      "instance-1866104e-fdb4-415b-83df-c2e7b662fac7"
    ], 
    "type": "ec2", 
    "volumes": {}
  }, 
  "eu13": {
    "aws_id": "i-74444f03", 
    "aws_private_dns_name": "ip-10-48-109-186.eu-west-1.compute.internal", 
    "aws_public_dns_name": "ec2-46-51-142-120.eu-west-1.compute.amazonaws.com", 
    "created": "2011-01-04T18:32:08", 
    "instance_type": "t1.micro", 
    "location": "eu-west-1", 
    "notes": null, 
    "os": "ubuntu-lucid-64-ebs", 
    "owner": "okfn", 
    "placement": "eu-west-1b", 
    "provider": "aws", 
    "security_groups": [
      "default", 
      "www-only", 
      "ssh-only", 
      "munin-only", 
      "instance-45ef52e6-3850-42d4-8484-0b7dcd18817a"
    ], 
    "type": "ec2", 
    "volumes": {}
  }, 
  "eu14": {
    "aws_id": "i-f60d1081", 
    "aws_private_dns_name": "ip-10-48-110-26.eu-west-1.compute.internal", 
    "aws_public_dns_name": "ec2-46-137-5-166.eu-west-1.compute.amazonaws.com", 
    "created": "2011-01-19T11:02:08", 
    "instance_type": "t1.micro", 
    "location": "eu-west-1", 
    "notes": null, 
    "os": "ubuntu-lucid-64-ebs", 
    "owner": "okfn", 
    "placement": "eu-west-1b", 
    "provider": "aws", 
    "security_groups": [
      "default", 
      "www-only", 
      "ssh-only", 
      "munin-only", 
      "instance-eu14"
    ], 
    "type": "ec2", 
    "volumes": {}
  }, 
  "eu15": {
    "aws_id": "i-515abc27", 
    "aws_private_dns_name": "ip-10-48-54-52.eu-west-1.compute.internal", 
    "aws_public_dns_name": "ec2-46-51-130-209.eu-west-1.compute.amazonaws.com", 
    "created": "2011-01-31T10:13:25", 
    "instance_type": "m1.small", 
    "location": "eu-west-1", 
    "notes": null, 
    "os": "ubuntu-lucid-32", 
    "owner": "okfn", 
    "placement": "eu-west-1b", 
    "provider": "aws", 
    "security_groups": [
      "default", 
      "www-only", 
      "ssh-only", 
      "munin-only", 
      "instance-eu15"
    ], 
    "type": "ec2", 
    "volumes": {}
  }, 
  "eu16": {
    "aws_id": "i-59a9582f", 
    "aws_private_dns_name": "ip-10-48-238-17.eu-west-1.compute.internal", 
    "aws_public_dns_name": "ec2-46-137-15-83.eu-west-1.compute.amazonaws.com", 
    "created": "2011-02-15T10:00:15", 
    "instance_type": "t1.micro", 
    "location": "eu-west-1", 
    "notes": null, 
    "os": "ubuntu-lucid-64-ebs", 
    "owner": "okfn", 
    "placement": "eu-west-1b", 
    "provider": "aws", 
    "security_groups": [
      "default", 
      "www-only", 
      "ssh-only", 
      "munin-only", 
      "instance-eu16"
    ], 
    "type": "ec2", 
    "volumes": {}
  }, 
  "eu18": {
    "aws_id": "i-09fe767f", 
    "aws_private_dns_name": "ip-10-48-146-139.eu-west-1.compute.internal", 
    "aws_public_dns_name": "ec2-46-137-55-23.eu-west-1.compute.amazonaws.com", 
    "created": "2011-05-13T12:31:17", 
    "instance_type": "m1.large", 
    "location": "eu-west-1", 
    "notes": null, 
    "os": "ubuntu-lucid-64", 
    "owner": "okfn", 
    "placement": "eu-west-1b", 
    "provider": "aws", 
    "security_groups": [
      "default", 
      "www-only", 
      "ssh-only", 
      "munin-only", 
      "instance-eu18"
    ], 
    "type": "ec2", 
    "volumes": {}
  }, 
  "eu2": {
    "aws_id": "i-2221f355", 
    "aws_ip": "ec2-79-125-24-227.eu-west-1.compute.amazonaws.com", 
    "cost per month": null, 
    "created": "2010", 
    "location": "eu-west-1b", 
    "notes": null, 
    "os": "debian-squeeze", 
    "owner": "okfn", 
    "provider": "aws", 
    "spec": "small", 
    "type": "ec2"
  }, 
  "eu3": {
    "aws_id": "i-2275d655", 
    "cost per month": null, 
    "created": "2010-03-15", 
    "location": "eu-west-1b", 
    "notes": null, 
    "os": "debian-lenny", 
    "owner": "okfn", 
    "provider": "aws", 
    "spec": "small", 
    "type": "ec2"
  }, 
  "eu4": {
    "aws_id": "i-38f1414f", 
    "aws_ip": "ec2-79-125-116-16.eu-west-1.compute.amazonaws.com", 
    "cost per month": "100", 
    "created": "2010-04", 
    "location": "eu-west-1b", 
    "os": "debian-squeeze", 
    "owner": "okfn", 
    "provider": "aws", 
    "spec": "large", 
    "type": "ec2"
  }, 
  "eu5": {
    "aws_id": "i-76ac2701", 
    "aws_ip": "ec2-46-51-130-232.eu-west-1.compute.amazonaws.com", 
    "created": "2010-06", 
    "location": "eu-west-1b", 
    "notes": "", 
    "os": "debian-squeeze", 
    "owner": "okfn", 
    "provider": "aws", 
    "spec": "large", 
    "type": "ec2"
  }, 
  "eu6": {
    "aws_id": "i-972153e0", 
    "aws_private_dns_name": "ip-10-227-3-101.eu-west-1.compute.internal", 
    "aws_public_dns_name": "ec2-46-51-189-76.eu-west-1.compute.amazonaws.com", 
    "created": "2010-08", 
    "location": "eu-west-1b", 
    "notes": "", 
    "os": "ubuntu-lucid", 
    "owner": "okfn", 
    "provider": "aws", 
    "spec": "small", 
    "type": "ec2"
  }, 
  "eu7": {
    "aws_id": "i-b54d35c2", 
    "aws_ip": " ec2-79-125-69-250.eu-west-1.compute.amazonaws.com", 
    "created": "2010-09", 
    "location": "eu-west-1b", 
    "notes": "", 
    "os": "ubuntu-lucid-32", 
    "owner": "okfn", 
    "provider": "aws", 
    "spec": "small", 
    "type": "ec2"
  }, 
  "eu8": {
    "aws_id": "i-7d5cdb0b", 
    "aws_private_dns_name": "ip-10-48-242-116.eu-west-1.compute.internal", 
    "aws_public_dns_name": "ec2-79-125-38-173.eu-west-1.compute.amazonaws.com", 
    "created": "2011-05-04T20:33:17", 
    "instance_type": "t1.micro", 
    "location": "eu-west-1", 
    "notes": null, 
    "os": "ubuntu-lucid-64-ebs", 
    "owner": "okfn", 
    "placement": "eu-west-1b", 
    "provider": "aws", 
    "security_groups": [
      "default", 
      "www-only", 
      "ssh-only", 
      "munin-only", 
      "instance-eu8"
    ], 
    "type": "ec2", 
    "volumes": {}
  }, 
  "eu9": {
    "aws_id": "i-f9eeb58e", 
    "aws_private_dns_name": "ip-10-227-38-29.eu-west-1.compute.internal", 
    "aws_public_dns_name": "ec2-46-51-139-166.eu-west-1.compute.amazonaws.com", 
    "created": "2010-10-27T15:30:40", 
    "instance_type": "t1.micro", 
    "location": "eu-west-1", 
    "notes": null, 
    "os": "ubuntu-lucid-64-ebs", 
    "owner": "okfn", 
    "placement": "eu-west-1b", 
    "provider": "aws", 
    "security_groups": [
      "default", 
      "www-only", 
      "ssh-only", 
      "munin-only", 
      "instance-339abc3c-450e-479b-a9b6-66852a2ceeb4"
    ], 
    "type": "ec2", 
    "volumes": {}
  }, 
  "us1": {
    "aws_id": "i-a83bb6c0", 
    "cost per month": null, 
    "created": "2009-10", 
    "location": "us-east-1d", 
    "notes": null, 
    "os": "debian-lenny", 
    "owner": "okfn", 
    "provider": "aws", 
    "spec": "small", 
    "type": "ec2"
  }, 
  "us10": {
    "cost per month": null, 
    "created": "2011-04", 
    "location": "ord1", 
    "notes": null, 
    "owner": "DataGM", 
    "provider": "rackspace", 
    "spec": "1GB", 
    "type": "cloud"
  }, 
  "us2": {
    "cost per month": null, 
    "created": "2009-10", 
    "location": "us-west", 
    "notes": null, 
    "owner": "okfn", 
    "provider": "dreamhost", 
    "spec": "small", 
    "type": "shared"
  }, 
  "us3": {
    "cost per month": null, 
    "created": "2011-03", 
    "location": "ord1", 
    "notes": null, 
    "owner": "LOD2", 
    "provider": "rackspace", 
    "spec": "1GB", 
    "type": "cloud"
  }, 
  "us4": {
    "cost per month": null, 
    "created": "2011-04", 
    "location": "ord1", 
    "notes": null, 
    "owner": "DataGM/NL", 
    "provider": "rackspace", 
    "spec": "1GB", 
    "type": "cloud"
  }, 
  "us5": {
    "cost per month": null, 
    "created": "2011-04", 
    "location": "ord1", 
    "notes": null, 
    "owner": "OKFN", 
    "provider": "rackspace", 
    "spec": "2GB", 
    "type": "cloud"
  }, 
  "us6": {
    "cost per month": null, 
    "created": "2011-03", 
    "location": "ord1", 
    "notes": null, 
    "owner": "OpenSpending", 
    "provider": "rackspace", 
    "spec": "4GB", 
    "type": "cloud"
  }, 
  "us7": {
    "cost per month": null, 
    "created": "2011-03", 
    "location": "ord1", 
    "notes": null, 
    "owner": "okf-dev", 
    "provider": "rackspace", 
    "spec": "2GB", 
    "type": "cloud"
  }, 
  "us8": {
    "cost per month": null, 
    "created": "2011-04", 
    "location": "ord1", 
    "notes": null, 
    "owner": "OKFN", 
    "provider": "rackspace", 
    "spec": "2GB", 
    "type": "cloud"
  }, 
  "us9": {
    "cost per month": null, 
    "created": "2011-04", 
    "location": "ord1", 
    "notes": null, 
    "owner": "OKFN", 
    "provider": "rackspace", 
    "spec": "2GB", 
    "type": "cloud"
  }
}