{
    "us1": {
        "owner": "okfn",
        "os": "debian-lenny",
        "created": "2009-10", 
        "aws_id": "i-a83bb6c0",
        "notes": null, 
        "location": "us-east-1d", 
        "provider": "aws", 
        "cost per month": null, 
        "type": "ec2", 
        "spec": "small"
    }, 
    "us2": {
        "owner": "okfn",
        "created": "2009-10", 
        "notes": null, 
        "location": "us-west", 
        "provider": "dreamhost", 
        "cost per month": null, 
        "type": "shared", 
        "spec": "small"
    }, 
    "us3": {
        "owner": "kforge",
        "created": "2010-02", 
        "notes": null, 
        "location": "us-east-1d", 
        "provider": "aws", 
        "cost per month": null, 
        "type": "ec2", 
        "spec": "small"
    }, 
    "eu0": {
        "owner": "okfn",
        "created": "2007", 
        "notes": null, 
        "location": "de", 
        "provider": "hentzner", 
        "cost per month": "49", 
        "type": "dedicated", 
        "spec": ""
    }, 
    "eu1": {
        "owner": "okfn",
        "created": "2008", 
        "notes": null, 
        "location": "uk", 
        "provider": "bytemark", 
        "cost per month": null, 
        "type": "dedicated-virtual", 
        "spec": null
    }, 
    "eu2": {
        "owner": "okfn",
        "os": "debian-squeeze",
        "aws_id": "i-2221f355",
        "aws_ip": "ec2-79-125-24-227.eu-west-1.compute.amazonaws.com",
        "created": "2010", 
        "notes": null, 
        "location": "eu-west-1b", 
        "provider": "aws", 
        "cost per month": null, 
        "type": "ec2", 
        "spec": "small"
    },
    "eu3": {
        "owner": "okfn",
        "os": "debian-lenny",
        "aws_id": "i-2275d655",
        "created": "2010-03-15", 
        "notes": null, 
        "location": "eu-west-1b", 
        "provider": "aws", 
        "cost per month": null, 
        "type": "ec2", 
        "spec": "small"
    }, 
    "eu4": {
        "owner": "okfn",
        "os": "debian-squeeze",
        "created": "2010-04", 
        "aws_id": "i-38f1414f", 
        "aws_ip": "ec2-79-125-116-16.eu-west-1.compute.amazonaws.com",
        "location": "eu-west-1b", 
        "provider": "aws", 
        "cost per month": "100", 
        "type": "ec2", 
        "spec": "large"
    }, 
    "eu5": {
        "owner": "okfn",
        "os": "debian-squeeze",
        "created": "2010-06", 
        "aws_id": "i-76ac2701", 
        "aws_ip": "ec2-46-51-130-232.eu-west-1.compute.amazonaws.com",
        "notes": "", 
        "location": "eu-west-1b", 
        "provider": "aws", 
        "type": "ec2", 
        "spec": "large"
    }, 
    "eu6": {
        "owner": "okfn",
        "os": "ubuntu-lucid",
        "created": "2010-08", 
        "aws_id": "i-972153e0", 
        "notes": "", 
        "location": "eu-west-1b", 
        "provider": "aws", 
        "type": "ec2", 
        "spec": "small"
    }, 
    "eu7": {
        "owner": "okfn",
        "os": "ubuntu-lucid-32",
        "created": "2010-09", 
        "aws_id": "i-b54d35c2", 
        "aws_ip": " ec2-79-125-69-250.eu-west-1.compute.amazonaws.com",
        "notes": "", 
        "location": "eu-west-1b", 
        "provider": "aws", 
        "type": "ec2", 
        "spec": "small"
    }, 
    "eu8": {
        "owner": "okfn",
        "os": "ubuntu-lucid-32",
        "created": "2010-09", 
        "aws_id": "i-b32e55c4",
        "aws_ip": "ec2-46-51-131-140.eu-west-1.compute.amazonaws.com",
        "location": "eu-west-1b",
        "provider": "aws", 
        "type": "ec2", 
        "spec": "small"
    }, 
    "eu9": {
        "placement": "eu-west-1b", 
        "created": "2010-10-27T15:30:40", 
        "os": "ubuntu-lucid-64-ebs", 
        "notes": null, 
        "provider": "aws", 
        "instance_type": "t1.micro", 
        "aws_public_dns_name": "ec2-46-51-139-166.eu-west-1.compute.amazonaws.com", 
        "location": "eu-west-1", 
        "volumes": {}, 
        "aws_private_dns_name": "ip-10-227-38-29.eu-west-1.compute.internal", 
        "owner": "okfn", 
        "type": "ec2", 
        "security_groups": [
            "default", 
            "www-only", 
            "ssh-only", 
            "munin-only", 
            "instance-339abc3c-450e-479b-a9b6-66852a2ceeb4"
        ], 
        "aws_id": "i-f9eeb58e"
    } ,
    "eu10": {
        "placement": "eu-west-1b", 
        "created": "2010-11-11T22:28:33", 
        "type": "ec2", 
        "notes": null, 
        "aws_private_dns_name": "ip-10-48-110-205.eu-west-1.compute.internal", 
        "instance_type": "t1.micro", 
        "aws_public_dns_name": "ec2-79-125-44-1.eu-west-1.compute.amazonaws.com", 
        "location": "eu-west-1", 
        "volumes": {}, 
        "provider": "aws", 
        "owner": "okfn", 
        "os": "ubuntu-maverick-64-ebs", 
        "security_groups": [
            "default", 
            "www-only", 
            "ssh-only", 
            "munin-only", 
            "instance-da69cda3-34e7-495c-ac12-7637228cbb19"
        ], 
        "aws_id": "i-03c9e674"
    }, 
    "eu11": {
        "placement": "eu-west-1b", 
        "created": "2010-11-14T21:24:09", 
        "type": "ec2", 
        "notes": null, 
        "aws_private_dns_name": "ip-10-227-139-160.eu-west-1.compute.internal", 
        "instance_type": "m1.large", 
        "aws_public_dns_name": "ec2-79-125-70-61.eu-west-1.compute.amazonaws.com", 
        "location": "eu-west-1", 
        "volumes": {}, 
        "provider": "aws", 
        "owner": "okfn", 
        "os": "ubuntu-lucid-64", 
        "security_groups": [
            "default", 
            "www-only", 
            "ssh-only", 
            "munin-only", 
            "instance-ef88b072-b285-422f-bc50-ed50a044f150"
        ], 
        "aws_id": "i-1da28b6a"
    }, 
    "eu12": {
        "placement": "eu-west-1b", 
        "created": "2010-11-27T19:46:29", 
        "type": "ec2", 
        "notes": null, 
        "aws_private_dns_name": "ip-10-226-107-164.eu-west-1.compute.internal", 
        "instance_type": "t1.micro", 
        "aws_public_dns_name": "ec2-46-51-142-222.eu-west-1.compute.amazonaws.com", 
        "location": "eu-west-1", 
        "volumes": {}, 
        "provider": "aws", 
        "owner": "okfn", 
        "os": "ubuntu-lucid-64-ebs", 
        "security_groups": [
            "default", 
            "www-only", 
            "ssh-only", 
            "munin-only", 
            "instance-1866104e-fdb4-415b-83df-c2e7b662fac7"
        ], 
        "aws_id": "i-b46a59c3"
    }, 
    "bkn-1": {
        "owner": "bkn",
        "aws_id": "i-29720e42",
        "ip": "184.73.208.200",
        "ip2": "ec2-184-73-208-200.compute-1.amazonaws.com us-east-1d",
        "provider": "aws",
        "type": "ec2",
        "location": "us-east-1d",
        "spec": "m1.small",
        "created": "2010-04-26"
    },
    "bkn-2": {
        "owner": "bkn",
        "notes": "krichel",
        "aws_id": "i-b18dbbda",
        "ip": "184.73.164.129",
        "provider": "aws",
        "type": "ec2",
        "location": "us-east-1d",
        "spec": "m1.small",
        "created": "2010-05-27"
    }
}
