---
hosted: aws
docker_host: true

##for nagios
sites_to_monitor:
  - pad.okfn.org:80:301 # monitor port 80, and check for status 200
  - booktype.okfn.org:80:200
  - sendy.okfn.org:80:301 # SSL redirect

ssl_sites_to_monitor:
  - pad.okfn.org
  - sendy.okfn.org

##for nginx
sites_enabled:
  - pad.okfn.org
  - booktype.okfn.org
  - sendy.okfn.org

nginx_ssl_certs:
  - star_okfn_org

# postfix config
postfix_additional_aliases: |
  school-of-data: /dev/null
postfix_additional_trusted_networks: "172.17.0.0/16"
postfix_transport: |
  school-of-data@lists.okfn.org local:
# We use recipient_access to enable restrictions on outbound mail from RT. Use
# DISCARD rather than reject (thus simulating successful delivery) to prevent
# RT's own postfix instance from accumulating failed deliveries in the queue.
postfix_recipient_access: |
  # Don't send emails to non-humans
  /^(noreply|no-reply|MAILER-DAEMON|nagios)@/ DISCARD
  # Don't send emails to our machines
  /^root@[^.]+\.okserver\.org/                DISCARD
postfix_sender_access: |
  tenderapp.com      REJECT
  pm.mtasv.net       REJECT
  rackspacecloud.com REJECT

postfix_smtpd_recipient_restrictions:
  - check_policy_service inet:127.0.0.1:10023

backup_scripts: ['mysql_backup.sh', 'psql_backup.sh']

#for mysql backups
backup_mysql: true
#snitches for backups
mysql_snitch: ecc09ca67b
psql_snitch: 304f7bf902
db_type: mysql
mysql_host: db002.cxglaymtrf0h.eu-west-1.rds.amazonaws.com
mysql_port: 3306


#for psql backups
backup_postgres: true
psql_host: db001.cxglaymtrf0h.eu-west-1.rds.amazonaws.com
psql_db_admin: dbadmin
psql_exclude_dbs:
  - farmsubsidy-org-production
  - openspending-org-production
  - postgres
  - rdsadmin
  - dbadmin

# openscience feed cron
openscience_cron: True
users_extra:
  - name: 'dfowler'
    groups:
      - sysadmin
    authorized_keys:
      - 'dfowler'
