#!/bin/bash

set -e

# The proper backup is done in with rsnapshot, see /etc/rsnapshot.conf
# This simple rsync copy w/o rotation is only for data that is unsuitable 
# for rsnapshot, e.g. large files that change frequently like VM image files
#
# This script assumes that local root can ssh as root into all sources.


# Space-separated list of sources. Do not forget the tailing slashes!
SOURCES="s031.okserver.org:/home/okfn/.vagrant.d/"
LANDING_ZONE="/home/backup/rsync-landingzones"


RSYNC="/usr/bin/rsync"
RSYNC_OPTIONS="--rsh=ssh --archive --sparse --compress"

NAME=$(basename $0)
PID_FILE=/var/run/${NAME}.pid
LOG_TAG="[${NAME}]"


if [ -f ${PID_FILE} ] ; then
    PID=`cat ${PID_FILE}`
    if [ -d /proc/${PID} ] ; then
        echo "ERROR: This job '${NAME}' is already running with pid ${PID}! Exiting." 1>&2
        exit 1
    fi
    echo "WARNING: removing stale pid file ${PID_FILE}" 1>&2
    rm ${PID_FILE}
fi 
echo $$  >  ${PID_FILE}
sleep 10

for source in ${SOURCES} ; do
    target="${LANDING_ZONE}/`echo ${source} | sed -e s,:,,`"

    ${RSYNC} ${RSYNC_OPTIONS} ${source} ${target}
done

rm ${PID_FILE}
