#!/bin/bash

set -eu

/usr/local/bin/aws s3 sync --sse /home/backup/mysql_backups/ s3://attic.okfn.org/mysql_backups/ --profile default 2>&1 > /home/backup/$(date +%s)_mysql_backup.log
/usr/local/bin/aws s3 sync --sse /home/backup/psql_backups/ s3://attic.okfn.org/psql_backups/ --profile default 2>&1 > /home/backup/$(date +%s)_psql_backup.log
find /home/backup/mysql_backups -mtime +14 -exec rm {} \;
find /home/backup/psql_backups -mtime +14 -exec rm {} \;
