#!/bin/sh

cd "$(dirname "$0")"

: ${CREDENTIALS_DIR:=$PWD/../../credentials}

set -eu

abort () {
  echo "ERROR: ${@}" >&2
  echo "Aborting." >&2
  exit 1
}

check_prereqs () {
  pip install -q -r requirements.txt

  # We need credentials to run
  if [ ! -d "$CREDENTIALS_DIR" ]; then
    abort "okfn/credentials must be checked out alongside this repository"
  fi

  # But we also need those credentials to be decrypted
  if ! GIT_DIR="$CREDENTIALS_DIR/.git" git config --local -l | 
       grep -q filter.git-crypt; then
    abort "${CREDENTIALS_DIR} must have been decrypted: see 'setup' in that directory"
  fi
}

check_prereqs
exec ansible-playbook \
  -i inventory/hosts \
  --extra-vars "private_dir='${CREDENTIALS_DIR}/ansible'" \
  "$@"
