#!/bin/bash

#set -eu

status() {

 echo "----> ${@}" >&2

}

etherpad_config=/src/etherpad-lite/settings.json

status "updating ${etherpad_config} with config"
sed -e 's/ETHERPAD_DBHOST/'${ETHERPAD_DBHOST}'/g' -i ${etherpad_config}
sed -e 's/ETHERPAD_DB/'${ETHERPAD_DB}'/g' -i ${etherpad_config}
sed -e 's/ETHERPAD_USER/'${ETHERPAD_USER}'/g' -i ${etherpad_config}
sed -e 's/ETHERPAD_PASS/'${ETHERPAD_PASS}'/g' -i ${etherpad_config}
sed -e 's/ADMIN_PASS/'${ADMIN_PASS}'/g' -i ${etherpad_config}

#status "checking if required DB and users exist..."
#check if etherpad db exists as root

#test if we can access the db as the created user
#mysql -u ${ETHERPAD_USER} -p ${ETHERPAD_PASS} -h ${ETHERPAD_DBHOST} ${ETHERPAD_DB} -e "show tables"
#if [ $? -ne 0 ];
#then
#        status "failed to access ${ETHERPAD_DB} using : mysql -u${ETHERPAD_USER} -p${ETHERPAD_PASS} -h${ETHERPAD_DBHOST}"
#        status "please make sure the etherpad user is created and can access the db properly"
#        exit 1
#fi


status "All systems are go!"

status "running supervisord"
exec /usr/bin/supervisord -n

